version: '3.8'

services:
  web:
    image: arm64v8/php:7.4-fpm
    container_name: php
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  nginx:
    image: arm64v8/nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - web

  db:
    image: arm64v8/mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
