version: '3.8'

services:
  web:
    image: arm64v8/php:7.4-fpm
    container_name: php
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  nginx:
    image: arm64v8/nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - web

  db:
    image: arm64v8/mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql

  runner:
    image: myoung34/github-runner:latest
    container_name: github_runner
    environment:
      REPO_URL: https://github.com/BaptisteLegat/web-php-bdd
      RUNNER_TOKEN: AS6ZEVT3YQPUJQSVZX23UXDGOAP44
      RUNNER_NAME: Ordinateur-portable-de-Baptiste
      RUNNER_WORKDIR: /tmp/github-runner
      RUNNER_GROUP: default
      ORG_RUNNER: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner:/runner
