name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo apt-get install -y docker-compose

      - name: Start Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be up
        run: sleep 30

      - name: Test the application
        run: curl -f http://localhost:8080

      - name: Stop Docker Compose
        run: docker-compose -f docker-compose.yml down
